name: ci-nodejs-workflow
on:
  pull_request:
    branches: [develop]
jobs:
   check-application:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: v16.14.2
      - run: npm start
      - name : test
        run: ./node_modules/.bin/jest test/calculator.test.js
      # - name: sonarCloud Scan
      #   uses: SonarSource/sonarcloud-github-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}